---
- name: Run security check script and collect results
  hosts: rocky_server
  become: yes
  tasks:
    - name: Copy check script to remote host
      copy:
        src: /tmp/semaphore/repository_2_1/check.sh
        dest: /tmp/check.sh
        mode: '0755'

    - name: Execute check script
      shell: /tmp/check.sh
      register: check_result

    - name: Fetch results from remote host
      fetch:
        src: "{{ check_result.stdout_lines[-1] }}"
        dest: "/home/ubuntu/{{ inventory_hostname }}_security_check.json"
        flat: yes

    - name: Remove temporary files
      file:
        path: /tmp/check.sh
        state: absent
