---
- name: Run Security Check Script
  hosts: all
  become: yes
  vars:
    script_path: /tmp/semaphore/repository_2_1/check.sh
    result_path: "/tmp/semaphore/repository_2_1/security_check_{{ ansible_date_time.date }}_{{ ansible_date_time.time }}.txt"
    json_path: "/tmp/semaphore/repository_2_1/security_check_{{ ansible_date_time.date }}_{{ ansible_date_time.time }}.json"

  tasks:
    - name: Copy security check script to remote host
      copy:
        src: /tmp/semaphore/repository_2_1/check.sh
        dest: "{{ script_path }}"
        mode: '0755'

    - name: Execute security check script
      shell: "{{ script_path }}"
      register: script_output

    - name: Display script output
      debug:
        var: script_output.stdout_lines

    - name: Convert result to JSON
      shell: |
        awk '
        BEGIN { print "{" }
        /^▶/ { 
          if (title) { print "  ]," }
          title = $0
          gsub(/^▶|◀$/, "", title)
          gsub(/"/, "\\\"", title)
          print "  \"" title "\": ["
          first = 1
        }
        /^※/ {
          if (!first) { print "    ," }
          first = 0
          result = $0
          gsub(/^※|결과 :/, "", result)
          gsub(/"/, "\\\"", result)
          print "    {\"result\": \"" result "\"}"
        }
        END { print "  ]" ; print "}" }
        ' {{ result_path }} > {{ json_path }}
      args:
        executable: /bin/bash

    - name: Fetch result file
      fetch:
        src: "{{ result_path }}"
        dest: "/tmp/semaphore/repository_2_1/security_check_results/"
        flat: yes

    - name: Fetch JSON file
      fetch:
        src: "{{ json_path }}"
        dest: "/tmp/semaphore/repository_2_1/security_check_results/"
        flat: yes

    - name: Remove script and result files from remote host
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ script_path }}"
        - "{{ result_path }}"
        - "{{ json_path }}"
